# ---- Build stage ----
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# Site-only build. public/data is generated by the `indexer` compose step
# BEFORE this image build and is picked up by `COPY . .` above — so the large
# archive tree is never copied into the image, only the small generated index.
RUN npm run build

# ---- Serve stage ----
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
